"""Rough, countable style numbers for the three voice sources.

Usage: python raz-elbaz-brand-identity-kit/voice/scripts/metrics.py > raz-elbaz-brand-identity-kit/voice/metrics.md

Sources:
  walla  raz-elbaz-brand-identity-kit/voice/corpus/*.txt (body only, header skipped)
  raz    raz-elbaz-brand-identity-kit/voice/raz-sample/messages.md, mostly-Hebrew messages only, with long
         quoted spans ("..." of 12+ words, usually text he pasted) removed
  site   Hebrew strings in the I18N table of src/page.html

Numbers are descriptive, not proof. Raz's messages are chat typed to a tool,
often without periods, so his "sentences" run long by construction; the
clause numbers (split on any punctuation) compare better.
"""
import collections, glob, os, re, statistics, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO = ROOT
while not os.path.exists(os.path.join(REPO, "build.py")) and REPO != os.path.dirname(REPO):
    REPO = os.path.dirname(REPO)   # the voice folder may sit deeper, e.g. inside the identity kit
HEB = re.compile(r"[֐-׿]")
LAT = re.compile(r"[A-Za-z]")
SENT = re.compile(r"(?<=[.?!…])\s+|\n+")
CLAUSE = re.compile(r"[.?!…,;:\n]+|\s[-–—]\s")
QUOTED = re.compile(r"[\"“”״]([^\"“”״]{60,}?)[\"“”״]")
MARKERS = ["בעצם", "פשוט", "ממש", "קצת", "טיפה", "אולי", "כביכול", "באמת", "בגדול", "דיי", "כאילו", "כמובן",
           "לגבי", "בוא", "יופי", "מעולה", "מושלם", "אוקיי", "אבל", "כי", "אז", "ככה", "כלומר", "למשל", "הרי", "בכלל"]
PRON = {"first_sg": r"\b(אני|לי|שלי|אותי)\b", "first_pl": r"\b(אנחנו|לנו|שלנו|אותנו)\b",
        "second": r"\b(אתם|אתן|לכם|שלכם|אתכם|אתה|לך|שלך)\b"}  # not את: mostly the object marker


def words(t):
    return [w for w in re.split(r"\s+", t) if HEB.search(w) or LAT.search(w) or w.isdigit()]


def walla():
    docs = []
    for f in sorted(glob.glob(os.path.join(ROOT, "corpus", "*.txt"))):
        text = open(f, encoding="utf-8").read()
        body = text.split("\n\n", 1)[1] if "\n\n" in text else text
        docs.append(body.strip())
    return docs


def raz():
    text = open(os.path.join(ROOT, "raz-sample", "messages.md"), encoding="utf-8").read()
    docs = []
    for chunk in text.split("\n---\n")[1:]:
        body = chunk.split("\n", 2)[-1].strip()
        body = QUOTED.sub(" ", body)
        if len(HEB.findall(body)) > 2 * len(LAT.findall(body)) and len(words(body)) >= 3:
            docs.append(body)
    return docs


def site():
    src = open(os.path.join(REPO, "src", "page.html"), encoding="utf-8").read()
    blk = src[src.index("const I18N = {"):src.index("/* =========================== STATE & HELPERS")]
    he = blk[blk.index("he: {"):blk.index("en: {")]
    pair = re.compile(r'([A-Za-z_0-9]+)\s*:\s*"((?:[^"\\]|\\.)*)"')
    out = []
    for k, v in pair.findall(he):
        v = re.sub(r"<[^>]+>", " ", v).replace("\\n", "\n").replace('\\"', '"')
        if len(HEB.findall(v)) > 20:
            out.append(v)
    return out


def stats(docs):
    text = "\n\n".join(docs)
    ws = words(text)
    n = len(ws) or 1
    sents = [s for d in docs for s in SENT.split(d) if len(words(s)) >= 1]
    sl = [len(words(s)) for s in sents]
    cl = [len(words(c)) for d in docs for c in CLAUSE.split(d) if words(c)]
    paras = [p for d in docs for p in re.split(r"\n\s*\n|\n", d) if words(p)]
    pl = [len(words(p)) for p in paras]
    per_k = lambda c: 1000 * c / n
    r = collections.OrderedDict()
    r["documents"] = len(docs)
    r["words"] = n
    r["sentence length, median words"] = statistics.median(sl) if sl else 0
    r["sentence length, mean words"] = round(statistics.mean(sl), 1) if sl else 0
    r["sentences of 1-6 words, %"] = round(100 * sum(1 for x in sl if x <= 6) / len(sl), 1) if sl else 0
    r["sentences of 25+ words, %"] = round(100 * sum(1 for x in sl if x >= 25) / len(sl), 1) if sl else 0
    r["clause length, median words"] = statistics.median(cl) if cl else 0
    r["paragraph length, median words"] = statistics.median(pl) if pl else 0
    r["questions per 1000 words"] = round(per_k(text.count("?")), 1)
    r["exclamations per 1000 words"] = round(per_k(text.count("!")), 1)
    r["commas per 1000 words"] = round(per_k(text.count(",")), 1)
    r["colons per 1000 words"] = round(per_k(text.count(":")), 1)
    r["dashes per 1000 words"] = round(per_k(len(re.findall(r"\s[-–—]\s", text))), 1)
    r["parentheses per 1000 words"] = round(per_k(text.count("(")), 1)
    for k, pat in PRON.items():
        r[f"{k} pronouns per 1000 words"] = round(per_k(len(re.findall(pat, text))), 1)
    return r, ws


def main():
    sys.stdout.reconfigure(encoding="utf-8")
    sources = {"walla": walla(), "raz": raz(), "site": site()}
    results, vocab = {}, {}
    for k, docs in sources.items():
        if docs:
            results[k], vocab[k] = stats(docs)
    cols = list(results)
    print("# Voice metrics\n")
    print("Generated by `raz-elbaz-brand-identity-kit/voice/scripts/metrics.py`. Descriptive only; see the script docstring for caveats.\n")
    print("| metric | " + " | ".join(cols) + " |")
    print("|---|" + "---|" * len(cols))
    for m in results[cols[0]]:
        print(f"| {m} | " + " | ".join(str(results[c][m]) for c in cols) + " |")
    print("\n## Marker words per 1000 words\n")
    print("| word | " + " | ".join(cols) + " |")
    print("|---|" + "---|" * len(cols))
    for w in MARKERS:
        row = []
        for c in cols:
            cnt = sum(1 for x in vocab[c] if re.sub(r"[^֐-׿]", "", x) in (w, "ו" + w, "ש" + w))
            row.append(f"{1000 * cnt / len(vocab[c]):.1f}")
        print(f"| {w} | " + " | ".join(row) + " |")


if __name__ == "__main__":
    main()
